DROP TABLE IF EXISTS poll;
DROP TABLE IF EXISTS bet;

CREATE TABLE poll (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  options VARCHAR(255) NOT NULL,
  correct_value INTEGER NOT NULL
);

CREATE TABLE bet (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  user_id VARCHAR(255) NOT NULL,
  created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  poll_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  poll_id INTEGER NOT NULL,
  choice INTEGER NOT NULL
);
